SELECT G.TITLE, G.BOARD_ID,	R.REPLY_ID, R.WRITER_ID, R.CONTENTS, date_format(R.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD G
    inner join USED_GOODS_REPLY R
        on G.BOARD_ID = R.BOARD_ID
where YEAR(G.CREATED_DATE) = 2022
and MONTH(G.CREATED_DATE) = 10
order by R.CREATED_DATE, G.TITLE
